oz-co-project-3/oz-co-project-3_backend

- app/core/config.py
- app/models/job_posting_model.py
- app/models/job_posting_models.py
- job_posting 기본 모델 작성
공공, 일반 / 공고 상태는 enum 처리 했습니다.
- reject_posting 기본 모델 작성
job_posting이 삭제되면 거절 이력도 삭제되어야 할까요...? - 일단 삭제되게 해두었습니다.
- Region 모델 작성
- Applicants 모델 작성
지원중, 지원 취소에 대한 상태 정보는 enum 처리 했습니다.
지원자가 삭제될 경우 해당 이력 또한 함께 삭제됩니다.
> ✨ Feat: job_posting 모델 작성

- README.md
> 이슈넘버 74
> Readme 내부에 초안 작성했습니다. 이후에 수정 될 예정입니다.
```
프론트 스택 변경 가능
핵심 기능 추가 예정
추가로 필요한 부분이 있을 경우 업데이트될 예정입니다.
```
>
> ✨Feat: Readme 파일 초안 작성

- app/api/routes/admin/admin_user.py
- app/api/routes/freeboard.py
- app/api/routes/success_review.py
> get_current_user 함수가 없어서 이준님이 fake_user로 사용하다 이준님이 만들어주신걸로 교체 했습니다.
어떤 변경 사항이 있나요?
```
```
> ✨Ref: get_current_user 수정

- app/api/routes/admin_user.py
- app/main.py
- app/schemas/admin/admin_resume_schemas.py
- app/schemas/admin/admin_user_schemas.py
- app/services/admin/admin_resume_services.py
- app/services/admin/admin_user_services.py
- app/utils/exception.py
> 21
> 관리자 이력서 전제,상세 조회 및 삭제 기능 API 제작
어떤 변경 사항이 있나요?
```
```
> ✨Feat: 관리자 이력서 API

- app/api/routes/admin_user.py
- app/main.py
- app/models/job_posting_models.py
- app/schemas/admin/admin_job_posting_schemas.py
- app/schemas/admin/admin_resume_schemas.py
- app/schemas/admin/admin_user_schemas.py
- app/services/admin/admin_job_posting_services.py
- app/services/admin/admin_resume_services.py
- app/services/admin/admin_user_services.py
- app/utils/exception.py
- migrations/models/1_20250411155350_update.py
> 25,26
> 관리자 공고 거절사유 생성 API, 공고 API 완성
어떤 변경 사항이 있나요?
```
```
> ✨Feat: 관리자 공고 API, 거절사유 생성

- app/tests/conftest.py
- app/tests/free_board_test.py
- poetry.lock
- pyproject.toml
> 84
> 테스트 코드 작성 및 테스트용 DB 제작
어떤 변경 사항이 있나요?
```
모듈 단위로 DB 연결되게 만들어 놨습니다
```
> ✨Feat: Free-board 테스트 코드 작성 및 테스트용 DB 제작

- app/api/routes/user.py
- app/core/redis.py
- app/core/token.py
- app/models/user_models.py
- app/schemas/user_schema.py
- app/services/auth_services.py
- app/services/email_services.py
- app/services/user_register_services.py
- migrations/models/1_20250413070513_update.py
- migrations/models/2_20250413151345_update.py
제목은 ✨Feat: user-api-email 인증 작성
> 이메일 인증부분 추가
> 기타 사항 리펙토링
어떤 변경 사항이 있나요?
```
회원가입 후 이메일 인증을 통해 인증이 완료된 사용자만 회원가입이 되도록 처리
User_models부분 필요없는 코드 정리
```
> 이메일 인증부분 자세히 들여다봐주세요
> 아직 .env로 처리를 안해 코드가 괜찮다 싶으면 향후 리펙토링을 통해 민감한 정보들(내 email smtp password)
은 .env로 관리를 진행하겠습니다.
> ✨Feat: user-api-email 인증 작성

- Dockerfile.dev
- Dockerfile.prod
- poetry.lock
- pyproject.toml
>
어떤 변경 사항이 있나요?
```
실행환경 유니콘에서 건니콘으로 바꿧어여
```
> ✨Feat: 환경 uvicorn -> gunicorn

- app/api/routes/websocket.py
- app/main.py
- nginx/conf.d/dev.conf
95
> 웹소켓 제작
어떤 변경 사항이 있나요?
```
```
> ✨Feat: websocket 코드 제작

- app/api/routes/postings.py
- app/main.py
- app/models/job_posting_models.py
- app/schemas/postings_schemas.py
- app/services/postings_services.py
- migrations/models/3_20250416035545_update.py
> 33~35
> 공고 전체조회,상세조회 및 지원 하기 수정 API 작성
어떤 변경 사항이 있나요?
```
```
> ✨Feat: 공고 전체조회,상세조회 및 지원 하기 수정 API 작성

- app/main.py
> CORS 설정
어떤 변경 사항이 있나요?
```
```
> ✨Feat: CORS 설정

- app/api/routes/user.py
- app/core/token.py
- app/schemas/user_schema.py
- app/services/user/auth_services.py
- app/services/user/social_services.py
> kakao 소셜 로그인 구현 완료
> naver 소셜 로그인 구현 완료
어떤 변경 사항이 있나요?
```
소셜 로그인 구현 완료했습니다.
소셜부분은 처음이다 보니 gpt 도움과 구글링 엄청나게 하면서 한거라
이건 이렇게 하면 좋겠다 싶은거 꼭 말씀주십쇼
그리고 naver같은경우는 개발단계에서는 싹 다 쓸 수 있는걸로 아는데
개발단계가아니라 배포단계에서는 못 쓰는건가요? 병학님 답변부탁
```
> ✨Feat: user-api-social 구현 완료

- app/api/routes/jobposting.py
- app/api/routes/public_api.py
- app/core/config.py
- app/main.py
- app/services/public_collection.py
- app/services/public_services.py
> 100
> 공공 api를 불러와서 테이블에 맞게 변형하여 저장하는 api를 구현했습니다.
샐러리를 이용해서 주기적으로 자동으로 불러오는 일은 아직 진행이 덜 되었습니다.
아마 router 내용은 수정이 될 것 같습니다.
.env에 들어가야할 내용은 따로 전달 드리겠습니다!
코드 리펙토링도 천천히 진행할게요
어떤 변경 사항이 있나요?
```
```
> ✨Feat: 외부 api 불러오는 기본 api 작성

- app/api/routes/postings.py
- app/services/postings_services.py
- migrations/models/4_20250420091028_update.py
> ✨Ref: 리팩토링을 위한 push

- app/api/v1/admin.py
- app/api/v1/user.py
- app/api/v1/websocket.py
- app/domain/job_posting/job_posting_models.py
- migrations/models/5_20250421061239_update.py
> 바뀐 경로 수정
어떤 변경 사항이 있나요?
```
```
> 🐛Fix: 경로 바뀐거 수정

- app/api/v1/chatbot.py
- app/api/v1/postings.py
- app/core/token.py
- app/domain/admin/services/admin_job_posting_services.py
- app/domain/admin/services/admin_resume_services.py
- app/domain/admin/services/admin_user_services.py
- app/domain/free_board/freeboard_services.py
- app/domain/posting/postings_services.py
- app/domain/success_review/success_review_services.py
- app/domain/user/services/auth_recovery_services.py
- app/tests/conftest.py
- app/tests/integration/admin_test.py
- app/tests/integration/chatbot_test.py
- app/tests/integration/comment_test.py
- app/tests/integration/free_board_test.py
> 경로 바뀐거 전부 수정 및 공고 전체조회 방법 리팩토링
어떤 변경 사항이 있나요?
```
```
> 🐛Fix: 경로 바뀐거 수정 및 공고 조회방법 리팩토링

- .github/workflows/deploy.yml
> ✨Ref: 배포서버 NPC -> AWS

- .github/workflows/deploy.yml
> ✨Ref: 배포서버 NCP -> AWS
어떤 변경 사항이 있나요?
```
```
> ✨Ref: 배포서버 NCP -> AWS

- .github/workflows/deploy.yml
> ✨Ref: 배포 구조 수정

- app/domain/comment/repository.py
- app/domain/comment/services.py
- app/utils/auth.py
> 126
> comment 리팩토링
어떤 변경 사항이 있나요?
```
```
> ✨Ref: comment 리팩토링

- app/domain/posting/repository.py
- app/domain/posting/schemas.py
- app/domain/posting/services.py
- app/utils/pagination.py
> pydatinc 에서 쿼리셋으로 받아서 깨지는 버그 수정
어떤 변경 사항이 있나요?
```
```
> ✨Fix: posting 쿼리셋으로 보내는 버그 수정

- app/api/v1/user.py
- app/domain/user/services/user_register_services.py
- app/domain/user/user_schema.py
> 이메일 중복검사 api 따로 제작
어떤 변경 사항이 있나요?
```
이메일 중복검사 따로 뺐습니다.
말고는 업습니다.
```
> ✨Feat: user-api 이메일 중복검사 수정

- app/domain/services/pagination.py
> 🐛 Fix:Delete app/domain/services/pagination.py

- app/api/v1/admin.py
- app/api/v1/postings.py
- app/domain/admin/schemas/admin_job_posting_schemas.py
- app/domain/posting/schemas.py
- app/domain/posting/services.py
> DTO 추가한 postings 리팩토링
어떤 변경 사항이 있나요?
```
```
> ⚡️Ref: posting 리팩토링

- app/domain/posting/schemas.py
> ⚡️Ref: postings 리팩토링

- app/api/v1/chatbot.py
- app/domain/chatbot/repository.py
- app/domain/chatbot/schemas.py
- app/domain/chatbot/services.py
> 128
> service 로직 분리 및 DTO 적용
어떤 변경 사항이 있나요?
```
```
> ⚡️Ref: chatbot 리팩토링

- app/api/v1/comment.py
- app/domain/comment/repository.py
- app/domain/comment/schemas.py
- app/domain/comment/services.py
> 126
> service 로직 분리 및 DTO 작성
어떤 변경 사항이 있나요?
```
```
> ⚡️Ref: comment 리팩토링

- app/domain/chatbot/repository.py
- app/domain/chatbot/services.py
> 챗봇 리팩토링 과정 오류 수정
어떤 변경 사항이 있나요?
```
```
> 🐛Fix: 챗봇 오류 수정

- app/tests/unit/test_unit_comment.py
> 149
> comment unit test 작성
어떤 변경 사항이 있나요?
```
```
> ✨Feat: comment unit 테스트 작성

- app/tests/unit/test_unit_chatbot.py
> 152
> 챗봇 유닛테스트 작성
어떤 변경 사항이 있나요?
```
```
> ✨Feat: chatbot unit 테스트 작성

- app/domain/admin/services/job_posting_services.py
- app/tests/unit/test_unit_admin/test_admin_job_posting.py
- app/tests/unit/test_unit_admin/test_admin_resume.py
- app/tests/unit/test_unit_admin/test_admin_user.py
> 154
> admin unit test 작성
어떤 변경 사항이 있나요?
```
```
> ✨Feat: admin unit 테스트 작성

- app/api/v1/websocket.py
> ✨챗봇 되돌리기 기능

- app/api/v1/jobposting.py
> 
> fake user > current user 받아오도록 변경
어떤 변경 사항이 있나요?
```
```
> 🐛 Bug : fake 유저 current로 변경

- app/api/v1/admin.py
- app/api/v1/chatbot.py
- app/api/v1/comment.py
- app/api/v1/freeboard.py
- app/api/v1/jobposting.py
- app/api/v1/postings.py
- app/api/v1/resume.py
- app/api/v1/success_review.py
- app/api/v1/user.py
- app/domain/job_posting/job_posting_models.py
- app/domain/services/s3_service.py
- app/main.py
- app/utils/s3_upload.py
- migrations/models/6_20250427073911_update.py
- poetry.lock
- pyproject.toml
> 스웨거 UI 텍스트 깨지 해결  
description 아래의 Text 는 마크다운 문법인데  
공백을 띄워쓰기로 처리해서 인덱스가 안으로 들어가는 문제  
공백 지우고 끝에 \n 으로 공통 되게 처리
API 설명 추가 및 title 변경
어떤 변경 사항이 있나요?
```
```
> ✨ Ref: 스웨거 문서 UI 수정

- app/domain/job_posting/job_posting_models.py
- app/domain/services/s3_service.py
- app/main.py
- app/utils/s3_upload.py
- migrations/models/6_20250427073911_update.py
- poetry.lock
- pyproject.toml
> 163
> FastAPI 서버 S3 연결 및 image 업로드 API 제작
어떤 변경 사항이 있나요?
```
```
> ✨Feat: S3 추가

- app/domain/admin/services/resume_services.py
> 🐛Fix: 임포트 오류 수정

- app/tests/conftest.py
- app/tests/unit/test_unit_admin/test_admin_job_posting.py
- app/tests/unit/test_unit_admin/test_admin_resume.py
- app/tests/unit/test_unit_chatbot.py
- app/tests/unit/test_unit_comment.py
- app/tests/unit/test_unit_services.py
> 테스트 코드 개선 및 수정  
service 단으로 check 하는 부분 분리 후  
check 부분만 unit 테스트 진행 함으로써 다른 원래 각 service 의 unittest check 부분 불필요 함으로써 제거
어떤 변경 사항이 있나요?
```
```
>  ⚡️Fix: TestCode 수정 및 개선

- app/api/v1/jobposting.py
- app/domain/job_posting/repository.py
- app/domain/job_posting/services.py
- app/exceptions/job_posting_exceptions.py
> 🐛 Fix: 404 에러 처리

- app/api/v1/applicant.py
- app/api/v1/jobposting.py
- app/api/v1/resume.py
- app/domain/applicant/services.py
- app/domain/job_posting/services.py
- app/domain/resume/repository.py
- app/domain/user/schema.py
- app/tests/integration/user_test_integration/profile_test.py
- app/tests/unit/user_test_unit/auth_test.py
> 🐛Fix: user

- app/api/v1/applicant.py
- app/api/v1/resume.py
- app/api/v1/user.py
- app/core/token.py
- app/domain/admin/schemas/user_schemas.py
- app/domain/free_board/schemas.py
- app/domain/job_posting/repository.py
- app/domain/job_posting/schema.py
- app/domain/job_posting/services.py
- app/domain/resume/service.py
- app/domain/services/email_detail.py
- app/domain/services/social_account.py
- app/domain/services/verification.py
- app/domain/user/repository.py
- app/domain/user/schema.py
- app/domain/user/services/auth_recovery_services.py
- app/domain/user/services/auth_services.py
> ⚡️Ref: 리팩토링

- app/api/v1/user.py
- app/domain/user/schema.py
- app/domain/user/services/auth_services.py
- app/domain/user/services/user_profile_services.py
> ✨Ref: 유저 logger추가 완료 / pydantic 응답구조 완료

- app/api/v1/applicant.py
- app/api/v1/postings.py
- app/api/v1/user.py
- app/domain/posting/services.py
- app/domain/user/repository.py
- app/domain/user/schema.py
- app/domain/user/services/auth_recovery_services.py
- app/domain/user/services/user_profile_services.py
- app/domain/user/services/user_register_services.py
- app/exceptions/user_exceptions.py
> 다중선택하게 코드 짜놨으나 다중선택하면 에러나게 발생한 코드 수정
어떤 변경 사항이 있나요?
```
```
> ⚡️Ref: user-리팩토링

- .github/workflows/checks.yml
- app/tests/conftest.py
- app/tests/integration/test_user/test_profile.py
- app/tests/integration/test_user/test_register.py
- app/tests/unit/test_user_unit/test_register_service.py
- poetry.lock
- pyproject.toml
> 테스트 환경 수정했습니다, 이제 CI 테스트 통과해야 성공했다 될겁니다 각자 테스트 코드 수정하시면 됩니다.
어떤 변경 사항이 있나요?
```
```
> ⚡️Ref : test 환경 sqlite -> postgres

- app/api/v1/postings.py
- app/domain/posting/schemas.py
- app/tests/integration/test_postings.py
> postings API 테스트코드 작성
어떤 변경 사항이 있나요?
```
```
> ✨Feat: postings 테스트코드 작성

- app/api/v1/user.py
- app/core/token.py
- app/domain/user/schema.py
- app/domain/user/services/auth_services.py
> 로그아웃 토큰 블랙리스트 추가 로직 작성
> pydantic 스키마 field값 추가 / 422에러 추가
어떤 변경 사항이 있나요?
```
```
> ✨Ref: 유저 로그아웃 토큰 블랙리스트 추가 / 422 에러 추가

- app/core/config.py
- app/core/redis.py
- app/core/settings.py
- app/core/token.py
- app/domain/services/business_verify.py
- app/domain/services/email_detail.py
- app/domain/services/social_account.py
- poetry.lock
- pyproject.toml
> pydantic-settings 적용 -> settings.py 에 모든 환경변수 주입, 외부 API, ORM 모델 등은 config.py 에 적용
어떤 변경 사항이 있나요?
```
```
> ✨Feat: pydantic-settings 라이브러리 사용

- app/core/token.py
- app/domain/admin/schemas/user_schemas.py
> 응답에 Optional 없어서 응답실패 해결
어떤 변경 사항이 있나요?
```
```
> 🐛 Fix: user response

- app/domain/job_posting/services.py
> 🐛 Fix: job-posting 코드 수정

- app/api/v1/admin.py
- app/domain/admin/repositories/resume_repository.py
- app/domain/admin/schemas/resume_schemas.py
- app/domain/admin/services/resume_services.py
> 관리자가 유저 한명당 전체 이력서 조회하는것으로 수정
어떤 변경 사항이 있나요?
```
```
> ✨Feat: 관리자 유저 이력서 전체 조회

- app/domain/applicant/schema.py
- app/domain/applicant/utils.py
> ⚡️Ref: 지원자 조회 응답 구조 변경

- app/tests/integration/test_jobposting.py
> 184
> 공고 작성 / 불러오기 / 디테일 / 수정 / 삭제 (기업회원) 테스트 작성
공고 북마크 (개인회원) 테스트 작성
어떤 변경 사항이 있나요?
> ✨ Feat : 공고 테스트 작성

- app/tests/integration/test_applicant.py
- app/tests/integration/test_jobposting.py
- app/tests/integration/test_resume.py
> 
> integration 테스트 완료
어떤 변경 사항이 있나요?
```
```
> ✨Feat : applicant integration 테스트 작성

- app/domain/admin/schemas/user_schemas.py
> ⚡️Ref: 어드민 유저 전체 조회 응답 구저 변경

- app/api/v1/user.py
- app/domain/services/social_account.py
- app/domain/user/services/user_register_services.py
> user 응답구조 변경 
어떤 변경 사항이 있나요?
```
```
> 🐛Fix: 유저 리다이렉트 구조 수정

- app/api/v1/resume.py
- app/domain/resume/service.py
> 🐛Fix:  이력서 응답 오류 수정

- app/api/v1/applicant.py
- app/domain/admin/schemas/resume_schemas.py
- app/domain/applicant/schema.py
- app/domain/services/social_account.py
- app/domain/user/services/auth_services.py
> 🐛Fix:  User 응답 오류 수정

- app/domain/job_posting/services.py
- app/domain/resume/schema.py
- app/domain/resume/service.py
- app/tests/integration/test_jobposting.py
- app/tests/integration/test_resume.py
> 
> 파이단틱 추가
타이틀 중복 검사 추가 (이력서 타이틀 중복 불가능)
타이틀 중복 검증을 위해 테스트 코드 수정
어떤 변경 사항이 있나요?
> 🐛 Ref: 레주메 리펙토링

- app/api/v1/postings.py
- app/domain/applicant/schema.py
- app/domain/applicant/services.py
- app/domain/applicant/utils.py
- app/domain/posting/repository.py
- app/domain/resume/service.py
- app/domain/services/permission.py
> Ref response

- Dockerfile.prod
> Ref dockerfile
